### PR TITLE
Update Runtime to 5.15-23.08

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by fedelibre** [comment]
Just yesterday night I thought about upgrading to 5.15-23.08.

I guess we need a more recent version of [Fontforge](https://github.com/fontforge/fontforge/releases)?

**Comment by JakobDev** [comment]
I can try to update it

**Comment by fedelibre** [comment]
I'm trying to build locally, but I have this annoying error:

```
$ flatpak-builder --install --user build org.frescobaldi.Frescobaldi.yaml 
Downloading sources
Downloading http://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Failed to download sources: module texgyre: The requested URL returned error: 404
```

That link works fine in a browser, but it doesn't work with wget (which I guess it's used by flatpak-builder?):

```
$ wget http://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip
--2023-10-25 14:57:22--  http://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip
Resolving www.gust.org.pl (www.gust.org.pl)... 158.75.62.7
Connecting to www.gust.org.pl (www.gust.org.pl)|158.75.62.7|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-25 14:57:22 ERROR 404: Not Found.
```

**Comment by fedelibre** [comment]
> Use https

Thanks, now it works

**Comment by fedelibre** [comment]
No, I wanted to try fixing the problem with the build of fontforge but I didn't have time yesterday.  On my computer I have an issue (related to gettext version) different from that of the CI here.
I'll send more info later today and push whatever I did so far.

**Comment by fedelibre** [comment]
No time today. I've just pushed the https fix.

**Comment by fedelibre** [comment]
The error was evident in the logs of my local build, while the logs in the Github CI were confusing.

I've just tested it and it seems to work fine.
I'll wait a few more days to let other test this build and then merge it next week.

**Pull request merged**
