### PR TITLE
Beta branch: install Frescobaldi from git master

### PR DESCRIPTION
**Pull request by fedelibre**

### CODE REVIEW

**Review by jeanas — APPROVED** [review]

**Comment by fedelibre** [comment]
Ok,  I cannot use the branch. The next build should pass.

**Comment by fedelibre** [comment]
Ooops, it won't work. I forgot we removed the Makefile. I should use the changes from #37

**Comment by fedelibre** [comment]
@jeanas Do you know why GitHub says "This branch cannot be rebased due to conflicts"?

I can do the merge locally without any problem. But I cannot push from the terminal and skip this PR because the beta branch is protected.

**Comment by fedelibre** [comment]
Ok, I got it. It depends on the merge method. The "rebase merge" is disabled because of conflicts, while the "create merge commit" method is enabled.

**Pull request merged**
