### PR TITLE
Use com.riverbankcomputing.PyQt.BaseApp

### PR DESCRIPTION
**Pull request by fedelibre**
and upgrade to KDE 5.15-21.08 runtime

### CODE REVIEW

**Comment by fedelibre** [comment]
Is this a random failure?

```
Updating org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
FB: Running 'flatpak --user update --subpath= -y --noninteractive org.freedesktop.Sdk.Extension.texlive/x86_64/21.08' on host
Updating runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
Error: Failed to update org.freedesktop.Sdk.Extension.texlive: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 is not available
FB: host_command_exited_cb 1583043 256
```

org.freedesktop.Sdk.Extension.texlive has the 21.08 branch (the default). Why it's not available?

**Comment by fedelibre** [comment]
bot, build

**Comment by fedelibre** [comment]
It's not a random error. I suspect there's a problem on flathub server, because a few hours ago [another user reported that he cannot install/update it](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/84).

**Comment by fedelibre** [comment]
Today I updated texlive extension successfully on my laptop. Hopefully it's been fixed.

bot, build

**Comment by fedelibre** [comment]
In aarch64 logs I don't see any error about texlive, but I see an oversight when I removed the shared-modules submodule:

```
]2;flatpak-builder: Downloading portmidi]2;flatpak-builder: Downloading portmidiFailed to download sources: module portmidi: Can't find file at shared-modules/pygame/portmidi-no-java.patch
```

I'll push a fix.

**Comment by fedelibre** [comment]
bot, build

**Comment by fedelibre** [comment]
bot, build

**Comment by hfiguiere** [comment]
My guess is that the version of sip python-poppler-qt5 want to use is incompatible with the one in the base app.

**Comment by fedelibre** [comment]
Replaced by #25

**Pull request closed without merging**
