### PR TITLE
Use PyQt.BaseApp

### PR DESCRIPTION
**Pull request by fedelibre**
Upgrade to poppler 21.08.0 and python-poppler-qt5 21.3.0. Remove Pango, as it's available in KDE runtime.

### CODE REVIEW

**Comment by fedelibre** [comment]
I see this:

    /bin/sh: line 1: clang-format: command not found

but I guess it's not the reason why the build was cancelled.

I'll try again...

**Comment by fedelibre** [comment]
bot, build

**Comment by fedelibre** [comment]
For the records, in my installations I see different font sizes between the current stable and this PR build, where the size is a bit larger. Don't know why...

Current stable:

frescobaldi-flatpak-stable

frescobaldi-flatpak-stable-versions


This PR build:

frescobaldi-flatpak-master

frescobaldi-flatpak-master-versions

**Comment by fedelibre** [comment]
I'll merge it and look at the font size issue later

**Comment by fedelibre** [comment]
@barthalion This PR was merged 4 days ago, but it's not been published yet.
On [buildbot](https://buildbot.flathub.org/#/apps/org.frescobaldi.Frescobaldi) you'll find:

- build 16937, committed and published 4 days ago when the PR was merged. But if I install or update my computer, I can't see it.
- build 17473, triggered manually by me yesterday and not published yet.

What's going on?

**Comment by barthalion** [comment]
There's an ongoing outage so publishing is currently paused. The queue will be processed later today. Please refer to [our status page](https://status.flathub.org/issues/2023-01-14-deltas/) in the future, I can't keep replying to every mention.

**Pull request merged**
