### PR TITLE
LilyPond 2.25.11

### PR DESCRIPTION
**Pull request by fedelibre**

### CODE REVIEW

**Comment by JakobDev** [comment]
sip is removed during the cleanup. I will add a option to keep sip.

**Comment by JakobDev** [comment]
Looks like I missread your comment. SIP is not needed during runtime.

**Comment by fedelibre** [comment]
> Looks like I missread your comment. SIP is not needed during runtime.

Yes, we need it only at build time. Please track the new sip release and update the PyQt.BaseApp as soon as 6.8.1 is released. Thanks!

**Comment by JakobDev** [comment]
6.8.1 has now been merged, but you need to wait until the new version is published.

**Comment by fedelibre** [comment]
bot, build

**Pull request merged**
