### PR TITLE
bump runtime version to 22.08

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by fedelibre** [comment]
The Python version in Frescobaldi manifest is hard-coded. 5.15-21.08 uses python 3.9. Which python version is 5.15-22.08 using?

Please note that Frescobaldi crashes with python 3.11. There's an open PR fixing this, but it's not completed yet.
See [issue 1453](https://github.com/frescobaldi/frescobaldi/issues/1453).

**Comment by jakobjakobson13** [comment]
> The Python version in Frescobaldi manifest is hard-coded. 5.15-21.08 uses python 3.9. Which python version is 5.15-22.08 using?
> 
> Please note that Frescobaldi crashes with python 3.11. There's an open PR fixing this, but it's not completed yet. See [issue 1453](https://github.com/frescobaldi/frescobaldi/issues/1453).

[freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-22.08.4/elements/include/python3.yml) says `python 3.10.6` for the release 22.08.4.

**Comment by fedelibre** [comment]
Let's wait for Frescobaldi 3.3 release before bumping the runtime version

**Comment by fedelibre** [comment]
replaced by #29

**Pull request closed without merging**
